name: Build and Release

on:
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        working-directory: src

      - name: Compile Windows Executable
        run: |
          compile.bat
        working-directory: src

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: CyberCraft-Windows
          path: src\dist\CyberCraft.exe

  build-macos:
    name: Build macOS Executable
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        working-directory: src

      - name: Compile macOS Executable
        run: |
          chmod +x *.sh resource/*.sh
          ./compile.sh
        working-directory: src

      - name: Upload macOS Executable
        uses: actions/upload-artifact@v4
        with:
          name: CyberCraft-macOS
          path: src/dist/CyberCraft
